version: '3.8'
services:
  api:
    build: .
    env_file: .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
