global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'artillery'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9466']