name: API Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master

jobs:
  api-test:
    name: Run API Tests in Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t auth-api .

      - name: Run API tests
        run: docker run --rm --env-file .env.test auth-api npm run test:api
