name: API Tests, Health Check & Security Scan

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev, master ]

jobs:
  api-tests:
    name: Run API Tests, Healthcheck & Trivy Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: docker compose build api-tests server

      - name: Run API tests
        run: docker compose run --rm api-tests

      - name: Clean up
        run: docker compose down

      - name: Build production image
        run: docker compose build server

      - name: Scan production image for vulnerabilities
        # Закрепляем актуальную версию, например, 0.52.0 на момент написания
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'api-test:prod'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Run healthcheck on production image
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          docker run -d --rm --name api-test-prod -p 3000:3000 \
            -e MONGO_URI="$MONGO_URI" \
            -e JWT_SECRET="$JWT_SECRET" \
            api-test:prod
          echo "Waiting for container to become healthy..."
          for i in {1..10}; do
            status=$(docker inspect --format='{{or .State.Health.Status "starting"}}' api-test-prod)
            echo "  → status is '$status'"
            if [ "$status" = "healthy" ]; then
              echo "✅ Container is healthy!"
              docker stop api-test-prod
              exit 0
            fi
            sleep 3
          done
          echo "❌ ERROR: Container failed healthcheck after 30 seconds."
          docker logs api-test-prod
          docker stop api-test-prod
          exit 1
