name: SonarQube Analysis

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps and run tests
        run: |
          npm ci
          npm run test -- --coverage

      - name: Sonar Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install --save-dev sonar-scanner
          npx sonar-scanner \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.host.url=https://your-sonarqube-server
