name: Unit Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev, master ]

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build unit-test image
        run: docker compose build unit-tests

      - name: Run unit tests
        run: docker compose run --rm unit-tests
