name: Unit Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev, master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build builder image
        run: docker build --target builder -t api-test:builder .

      - name: Run unit tests
        run: docker run --rm -e NODE_ENV=test api-test:builder npm run test:unit
